name: smart_home_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^2.2.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  smooth_page_indicator: ^1.0.1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  provider: ^6.0.5
  flutter_animate: ^3.0.0
  flutter_spinkit: ^5.1.0
  slide_to_act: ^2.0.1
  curved_navigation_bar: ^1.0.3
  hidden_drawer_menu: ^3.0.1
  cloud_firestore: ^4.5.0
  percent_indicator: ^4.2.3
  dropdown_button2: ^1.9.2
  liquid_pull_to_refresh: ^3.0.1
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
