// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqOrmxCbV40WTXTptio8tHldqJHxWD1E',
    appId: '1:713884072930:android:00c85a1aff190aadf2d7bb',
    messagingSenderId: '713884072930',
    projectId: 'fitness-app-2-69c87',
    storageBucket: 'fitness-app-2-69c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxuOW2-r_dAQ1k_eiuxqrqYKIrECAtiYQ',
    appId: '1:713884072930:ios:1fe3d95731eef53af2d7bb',
    messagingSenderId: '713884072930',
    projectId: 'fitness-app-2-69c87',
    storageBucket: 'fitness-app-2-69c87.firebasestorage.app',
    iosBundleId: 'com.adrianskiba.smartHomeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FQ0VNH38NVDGpM4W-eGFJdCLmekTCao',
    appId: '1:713884072930:web:fc8644074c3181a9f2d7bb',
    messagingSenderId: '713884072930',
    projectId: 'fitness-app-2-69c87',
    authDomain: 'fitness-app-2-69c87.firebaseapp.com',
    storageBucket: 'fitness-app-2-69c87.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxuOW2-r_dAQ1k_eiuxqrqYKIrECAtiYQ',
    appId: '1:713884072930:ios:203a560542fe3af2f2d7bb',
    messagingSenderId: '713884072930',
    projectId: 'fitness-app-2-69c87',
    storageBucket: 'fitness-app-2-69c87.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0FQ0VNH38NVDGpM4W-eGFJdCLmekTCao',
    appId: '1:713884072930:web:03474c9ed9cb4a66f2d7bb',
    messagingSenderId: '713884072930',
    projectId: 'fitness-app-2-69c87',
    authDomain: 'fitness-app-2-69c87.firebaseapp.com',
    storageBucket: 'fitness-app-2-69c87.firebasestorage.app',
  );

}